batch_size: 1
chemical_symbols:
- C
- S
- F
- H
- N
- O
dataset: ase
dataset_file_name: project_resources/nequip/positions/scaffold_splitter/HLC_train_mol_positions.extxyz
dataset_seed: 456
dataset_url: ''
key_mapping:
  E: total_energy
  R: pos
  z: atomic_numbers
l_max: 2
loss_coeffs: total_energy
max_epochs: 3
model_builders:
- SimpleIrrepsConfig
- EnergyModel
- PerSpeciesRescale
- RescaleEnergyEtc
n_train: 120
n_val: 31
npz_fixed_field_keys:
- atomic_numbers
num_basis: 8
num_features: 16
optimizer_name: Adam
parity: true
r_max: 4.0
root: P450
run_name: HLC_scaff
seed: 123
wandb: 'false'
wandb_project: ''
