batch_size: 1
chemical_symbols:
- P
- I
- Cl
- S
- N
- H
- F
- C
- Br
- B
- O
dataset: ase
dataset_file_name: project_resources/nequip/positions/random/RLM_train_mol_positions.extxyz
dataset_seed: 456
dataset_url: ''
key_mapping:
  E: total_energy
  R: pos
  z: atomic_numbers
l_max: 2
loss_coeffs: total_energy
max_epochs: 3
model_builders:
- SimpleIrrepsConfig
- EnergyModel
- PerSpeciesRescale
- RescaleEnergyEtc
n_train: 5
n_val: 5
npz_fixed_field_keys:
- atomic_numbers
num_basis: 8
num_features: 16
optimizer_name: Adam
parity: true
r_max: 4.0
root: project_resources/nequip
run_name: RLM_rand
seed: 123
wandb: 'false'
wandb_project: ''
